# Generated by Django 4.1.4 on 2023-05-11 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='promo',
            field=models.BooleanField(default=False),
        ),
    ]
