# Generated by Django 4.1.4 on 2023-05-11 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0003_measurement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='unit',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='coreapp.measurement'),
        ),
    ]
