# Generated by Django 4.1.4 on 2023-05-11 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0004_alter_products_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='unit',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='coreapp.measurement'),
        ),
    ]
